### ISSUE TITLE
[Bug?] Crouch not applies while opening menus/using interactive blocks

### ISSUE THREAD

**Issue by SyberiaK** [MrMelon54/auto-crouch-fabric#2]
Auto Crouch is not working while opening menus or using interactive blocks like workbench or chest. The only condition I found when it works is only while opening chat.
Is that how it should be?

**Comment by mrmelon54** [comment]
what version are you using?

**Comment by SyberiaK** [comment]
The latest from Modrinth mod page.

**Comment by mrmelon54** [comment]
Try looking in the config (using modmenu). There is a screens tab that has switches for individual interactive screens.

**Comment by SyberiaK** [comment]
Well, now I'm sure this is a real bug.
![изображение](https://user-images.githubusercontent.com/97897772/173821979-f3738436-dd6a-4d89-b4e2-95334ee4d063.png)

**Comment by mrmelon54** [comment]
Unfortunately some of them are missing in-game but work fine in a development environment

**Comment by SyberiaK** [comment]
Could this issue be caused by another mod? I have about 64 mods installed, so maybe one of them breaks something

**Comment by mrmelon54** [comment]
you could try with just my mod, fabric api and mod menu (to edit configs)

**Comment by SyberiaK** [comment]
Well, still not works

**Comment by mrmelon54** [comment]
damn ok, I'll look into it

**Comment by mrmelon54** [comment]
I have a solution.. I'll probably release it later in v3.0.2
Just fixing creative mode flying in v3.0.1

**Comment by mrmelon54** [comment]
Updated the mod and moved to a new repo, if the issue still persists please create an issue on: https://github.com/mrmelon54/auto_crouch
