### ISSUE TITLE
crashes when I change an option in config

### ISSUE THREAD

**Issue by Aces-and-Jacks** [MrMelon54/auto-crouch-fabric#4]
https://mclo.gs/n0xc0sw

1.19.2
quilt

When I changed the GUI menu off in the config then on it crashed

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/ZeHApfs

Here's a shorter list
Able to reproduce. When I open config and change gui option to no it crashes

**Comment by mrmelon54** [comment]
This will definitely be fixed as part of a bigger rewrite I'm working on. Unfortunately I don't have endless time so it's still in progress.

**Comment by mrmelon54** [comment]
Updated the mod and moved to a new repo, if the issue still persists please create an issue on: https://github.com/mrmelon54/auto_crouch
